package miniJava.SyntacticAnalyzer;

public enum TokenKind {ID, NUM, 
						LESSTHAN, GREATERTHAN, LESSTHANEQUAL, GREATERTHANEQUAL, 
						AND, OR, 
						LOGICALNEGATIVE, NOTEQUAL,
						PLUS, TIMES, DIVIDE, MINUSORARITHMETICNEGATIVE,
						ASSIGNMENTEQUAL, LOGICALEQUAL,
						EOT, ERROR, 
						LEFTBRACKET, RIGHTBRACKET, LEFTSQUAREBRACKET, RIGHTSQUAREBRACKET, 
						LEFTPAREN, RIGHTPAREN, SEMICOLON, COMMA, DOT,
						TRUE, FALSE, CLASS, VOID, PUBLIC, PRIVATE, STATIC, NEW, 
						RETURN, IF, ELSE, WHILE, INT, BOOLEAN, THIS, NULL
						
						}
