package miniJava.SyntacticAnalyzer;

public enum TokenKind {ID, NUM, INT, BOOLEAN,
						LESSTHAN, GREATERTHAN, LESSTHANEQUAL, GREATERTHANEQUAL, 
						AND, OR, 
						LOGICALNEGATIVE, NOTEQUAL,
						PLUS, TIMES, DIVIDE, 
						ASSIGNMENTEQUALS, LOGICALEQUAL,
						EOT, ERROR, 
						MINUS, ARITHMETICNEGATIVE,
						LEFTBRACKET, RIGHTBRACKET, LEFTSQUAREBRACKET, RIGHTSQUAREBRACKET, 
						LEFTPAREN, RIGHTPAREN, SEMICOLON, COMMA, DOT,
						TRUE, FALSE, CLASS, VOID, PUBLIC, PRIVATE, STATIC, NEW, 
						RETURN, IF, ELSE, WHILE,
						}
